import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'antd/dist/reset.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.scss'; 
import StyledComponentsRegistry from '@/lib/antd.registry'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}> 
                    <StyledComponentsRegistry>
                        {children} 
                    </StyledComponentsRegistry> 
            </body>
        </html>
    );
}
